CREATE DATABASE QLSACH

GO

USE QLSACH

GO

CREATE TABLE SACH(
	MASACH VARCHAR(10) NOT NULL,
	TENSACH NVARCHAR(50) NOT NULL,
	TACGIA NVARCHAR(30) NOT NULL,
	NHAXB NVARCHAR(50),
	NAMXB INT,
	PRIMARY KEY(MASACH)
)

GO

CREATE TABLE DOCGIA(
	MADG VARCHAR(10) NOT NULL,
	HOTEN NVARCHAR(30) NOT NULL,
	NGAYSINH DATE,
	DIACHI NVARCHAR(30),
	NGHENGHIEP NVARCHAR(30),
	PRIMARY KEY(MADG)
)

GO

CREATE TABLE PHIEUMUON(
	SOPM VARCHAR(10) NOT NULL,
	MADG VARCHAR(10) NOT NULL,
	PRIMARY KEY(SOPM)
)

GO

CREATE TABLE PHIEUCHITIET(
	SOPM VARCHAR(10) NOT NULL,
	MASACH VARCHAR(10) NOT NULL,
	SOLUONG INT,
	NGAYMUON DATE,
	PRIMARY KEY(SOPM, MASACH)
)

GO

ALTER TABLE PHIEUMUON ADD CONSTRAINT FK_MADG_PM FOREIGN KEY(MADG) REFERENCES DOCGIA(MADG)

GO

ALTER TABLE PHIEUCHITIET ADD CONSTRAINT FK_SOPM_PCT FOREIGN KEY(SOPM) REFERENCES PHIEUMUON(SOPM)

GO

ALTER TABLE PHIEUCHITIET ADD CONSTRAINT FK_MASACH_PCT FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)